name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Check out LFS objects
      run: git lfs checkout

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libopencv-dev make clang-tidy

    - name: Build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build

    # If you know how to get cmake to fail the build if clang-tidy exists non-zero please tell me
    - name: Build project
      run: |
        cmake --build build 2>&1 | tee build.log
        if grep -Eq 'warning:|error:' build.log; then
            exit 1
        fi

    - name: Run tests
      working-directory: ./build
      run: ARGS=--output-on-failure make test
